# Generated by Django 6.0.5 on 2026-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overall', models.IntegerField()),
                ('pace', models.IntegerField()),
                ('shooting', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('defending', models.IntegerField()),
                ('physical', models.IntegerField()),
                ('playstyles', models.IntegerField()),
                ('playstyle_plus', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
