# Generated by Django 6.0.5 on 2026-06-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_playercard_image_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='income',
            field=models.IntegerField(default=10),
        ),
    ]
