# Generated by Django 6.0.5 on 2026-07-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_teamcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='rarity',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('legendary', 'Legendary')], default='bronze', max_length=20),
        ),
    ]
