# Generated by Django 6.0.5 on 2026-07-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_playercard_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('bronze_chance', models.IntegerField(default=60)),
                ('silver_chance', models.IntegerField(default=25)),
                ('gold_chance', models.IntegerField(default=12)),
                ('legendary_chance', models.IntegerField(default=3)),
            ],
        ),
    ]
