# Generated by Django 6.0.5 on 2026-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('ATT', 'Attacker')], default='ATT', max_length=3),
        ),
    ]
